// Category Actions Types
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORY = 'GET_CATEGORY';
export const CATEGORIES_ERROR = 'CATEGORIES_ERROR';

// Product Action Types
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT = 'GET_PRODUCT';
export const PRODUCTS_ERROR = 'PRODUCTS_ERROR';
export const GET_TOP_SELLING_PRODUCTS = 'GET_TOP_SELLING_PRODUCTS';
export const GET_NEW_ARRIVALS_PRODUCTS = 'GET_NEW_ARRIVALS_PRODUCTS';
export const GET_PROMOTIONAL_PRODUCTS = 'GET_PROMOTIONAL_PRODUCTS'; 
export const GET_CATEGORY_PRODUCTS = 'GET_CATEGORY_PRODUCTS';
export const GET_FILTERED_CATEGORY_PRODUCTS = 'GET_FILTERED_CATEGORY_PRODUCTS'; 

// Authentication Action Types
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGOUT = 'LOGOUT';

// Cart Action Types
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL';
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const GET_CART_FAIL = 'GET_CART_FAIL';
export const UPDATE_CART_ITEM_SUCCESS = 'UPDATE_CART_ITEM_SUCCESS';
export const UPDATE_CART_ITEM_FAIL = 'UPDATE_CART_ITEM_FAIL';
export const REMOVE_CART_ITEM_SUCCESS = 'REMOVE_CART_ITEM_SUCCESS';
export const REMOVE_CART_ITEM_FAIL = 'REMOVE_CART_ITEM_FAIL';
export const CLEAR_CART_SUCCESS = 'CLEAR_CART_SUCCESS';
export const CLEAR_CART_FAIL = 'CLEAR_CART_FAIL';
export const CART_LOADING = 'CART_LOADING';
